-- ============================================================================
-- Migration: Initial Schema for 10x-cards
-- ============================================================================
-- Purpose: Creates the foundational database schema for the flashcard application
--          supporting AI-generated and manual flashcards with generation tracking.
--
-- Tables created:
--   - generation_sessions: Stores metadata for successful AI generation sessions
--   - flashcards: Stores user flashcards (AI-generated and manual)
--   - generation_error_logs: Stores logs for failed AI generation attempts
--
-- Types created:
--   - flashcard_source: ENUM type for flashcard origin (ai_generated, manual)
--
-- Security:
--   - Row Level Security (RLS) enabled on all tables
--   - All data is user-scoped (users can only access their own data)
--   - Anonymous users have no access to any table
--
-- Notes:
--   - Uses Supabase's auth.users for user management
--   - CASCADE DELETE ensures GDPR compliance (user deletion removes all data)
--   - moddatetime extension used for automatic updated_at timestamps
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Extensions
-- ----------------------------------------------------------------------------
-- Enable moddatetime extension for automatic timestamp updates
-- This extension provides a trigger function that sets a column to current timestamp
create extension if not exists moddatetime;

-- ----------------------------------------------------------------------------
-- Custom Types
-- ----------------------------------------------------------------------------
-- flashcard_source: Distinguishes between AI-generated and manually created flashcards
-- Using ENUM ensures data integrity and efficient storage/querying
create type flashcard_source as enum ('ai_generated', 'manual');

-- ----------------------------------------------------------------------------
-- Tables
-- ----------------------------------------------------------------------------

-- generation_sessions: Stores metadata for successful AI generation sessions
-- Created first because flashcards table references it via foreign key
create table generation_sessions (
    id uuid primary key default gen_random_uuid(),

    -- Reference to Supabase auth user
    -- CASCADE ensures all sessions are deleted when user is deleted (GDPR compliance)
    user_id uuid not null references auth.users(id) on delete cascade,

    -- The source text that was used to generate flashcards
    -- Constrained to 1000-10000 characters as per business requirements
    source_text text not null,

    -- Name/identifier of the AI model used for generation (e.g., 'gpt-4', 'claude-3')
    -- VARCHAR instead of ENUM allows adding new models without migrations
    model_used varchar(100) not null,

    -- Number of flashcards generated by AI in this session
    generated_count integer not null,

    -- Number of flashcards accepted by user (NULL until session is finalized)
    -- Allows tracking acceptance rate for analytics
    accepted_count integer,

    created_at timestamptz not null default now(),

    -- Constraint: source_text must be between 1000 and 10000 characters
    constraint generation_sessions_source_text_length
        check (char_length(source_text) >= 1000 and char_length(source_text) <= 10000),

    -- Constraint: generated_count must be non-negative
    constraint generation_sessions_generated_count_positive
        check (generated_count >= 0),

    -- Constraint: accepted_count must be non-negative when not NULL
    constraint generation_sessions_accepted_count_positive
        check (accepted_count is null or accepted_count >= 0)
);

-- Add comment to table for documentation
comment on table generation_sessions is 'Stores metadata for successful AI flashcard generation sessions';

-- flashcards: Core table storing all user flashcards
create table flashcards (
    id uuid primary key default gen_random_uuid(),

    -- Reference to Supabase auth user
    -- CASCADE ensures all flashcards are deleted when user is deleted (GDPR compliance)
    user_id uuid not null references auth.users(id) on delete cascade,

    -- Optional reference to the generation session that created this flashcard
    -- NULL for manually created flashcards
    -- SET NULL preserves flashcards when their generation session is deleted
    generation_id uuid references generation_sessions(id) on delete set null,

    -- Front side of the flashcard (question/prompt)
    -- Constrained to 1-500 characters
    front varchar(500) not null,

    -- Back side of the flashcard (answer)
    -- Constrained to 1-2000 characters
    back varchar(2000) not null,

    -- Indicates whether the flashcard was AI-generated or manually created
    -- Defaults to 'manual' for user-created flashcards
    source flashcard_source not null default 'manual',

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    -- Constraint: front must be between 1 and 500 characters
    constraint flashcards_front_length
        check (char_length(front) >= 1 and char_length(front) <= 500),

    -- Constraint: back must be between 1 and 2000 characters
    constraint flashcards_back_length
        check (char_length(back) >= 1 and char_length(back) <= 2000)
);

-- Add comment to table for documentation
comment on table flashcards is 'Stores user flashcards, both AI-generated and manually created';

-- generation_error_logs: Stores logs for failed AI generation attempts
-- Useful for debugging, monitoring, and improving AI generation reliability
create table generation_error_logs (
    id uuid primary key default gen_random_uuid(),

    -- Reference to Supabase auth user
    -- CASCADE ensures all error logs are deleted when user is deleted (GDPR compliance)
    user_id uuid not null references auth.users(id) on delete cascade,

    -- The source text that was used in the failed generation attempt
    -- Stored for debugging and potential retry analysis
    source_text text not null,

    -- Error code for categorization (e.g., 'API_TIMEOUT', 'INVALID_RESPONSE', 'RATE_LIMIT')
    error_code varchar(50) not null,

    -- Detailed error message for debugging
    error_message text not null,

    -- Name/identifier of the AI model that was used
    model_used varchar(100) not null,

    created_at timestamptz not null default now(),

    -- Constraint: source_text must be between 1000 and 10000 characters
    constraint generation_error_logs_source_text_length
        check (char_length(source_text) >= 1000 and char_length(source_text) <= 10000)
);

-- Add comment to table for documentation
comment on table generation_error_logs is 'Stores logs for failed AI flashcard generation attempts for debugging and analytics';

-- ----------------------------------------------------------------------------
-- Indexes
-- ----------------------------------------------------------------------------

-- Index for efficient lookup of user's flashcards
-- Most common query pattern: fetching all flashcards for a specific user
create index idx_flashcards_user_id on flashcards(user_id);

-- Index for foreign key: flashcards.generation_id -> generation_sessions.id
-- Required for efficient CASCADE operations and JOIN queries
-- Without this index, DELETE on generation_sessions would cause full table scan on flashcards
create index idx_flashcards_generation_id on flashcards(generation_id);

-- Composite index for fetching user's generation history ordered by date
-- Supports queries like: "Show user's generation sessions, newest first"
create index idx_generation_sessions_user_id_created_at
    on generation_sessions(user_id, created_at desc);

-- Index for efficient lookup of user's error logs
create index idx_generation_error_logs_user_id on generation_error_logs(user_id);

-- ----------------------------------------------------------------------------
-- Row Level Security (RLS)
-- ----------------------------------------------------------------------------
-- Enable RLS on all tables to enforce data isolation between users
-- With RLS enabled, users can only access rows that match their policies
-- By default (with no matching policy), all access is denied

alter table flashcards enable row level security;
alter table generation_sessions enable row level security;
alter table generation_error_logs enable row level security;

-- ----------------------------------------------------------------------------
-- RLS Policies: flashcards
-- ----------------------------------------------------------------------------
-- Users can only access their own flashcards
-- Each operation (SELECT, INSERT, UPDATE, DELETE) has a separate policy

-- SELECT: Users can view only their own flashcards
create policy "flashcards_select_authenticated"
    on flashcards for select
    to authenticated
    using (user_id = (select auth.uid()));

-- INSERT: Users can only create flashcards for themselves
-- WITH CHECK ensures the user_id in the new row matches the authenticated user
create policy "flashcards_insert_authenticated"
    on flashcards for insert
    to authenticated
    with check (user_id = (select auth.uid()));

-- UPDATE: Users can only update their own flashcards
-- USING clause filters which rows can be updated
-- WITH CHECK ensures the user_id isn't changed to another user
create policy "flashcards_update_authenticated"
    on flashcards for update
    to authenticated
    using (user_id = (select auth.uid()))
    with check (user_id = (select auth.uid()));

-- DELETE: Users can only delete their own flashcards
create policy "flashcards_delete_authenticated"
    on flashcards for delete
    to authenticated
    using (user_id = (select auth.uid()));

-- ----------------------------------------------------------------------------
-- RLS Policies: generation_sessions
-- ----------------------------------------------------------------------------
-- Users can only access their own generation sessions

-- SELECT: Users can view only their own generation sessions
create policy "generation_sessions_select_authenticated"
    on generation_sessions for select
    to authenticated
    using (user_id = (select auth.uid()));

-- INSERT: Users can only create generation sessions for themselves
create policy "generation_sessions_insert_authenticated"
    on generation_sessions for insert
    to authenticated
    with check (user_id = (select auth.uid()));

-- UPDATE: Users can only update their own generation sessions
-- Primarily used to set accepted_count after user reviews generated flashcards
create policy "generation_sessions_update_authenticated"
    on generation_sessions for update
    to authenticated
    using (user_id = (select auth.uid()))
    with check (user_id = (select auth.uid()));

-- DELETE: Users can only delete their own generation sessions
create policy "generation_sessions_delete_authenticated"
    on generation_sessions for delete
    to authenticated
    using (user_id = (select auth.uid()));

-- ----------------------------------------------------------------------------
-- RLS Policies: generation_error_logs
-- ----------------------------------------------------------------------------
-- Users can only access their own error logs
-- Note: No UPDATE policy as error logs should be immutable once created

-- SELECT: Users can view only their own error logs
create policy "generation_error_logs_select_authenticated"
    on generation_error_logs for select
    to authenticated
    using (user_id = (select auth.uid()));

-- INSERT: Users can only create error logs for themselves
-- Typically created by the backend when AI generation fails
create policy "generation_error_logs_insert_authenticated"
    on generation_error_logs for insert
    to authenticated
    with check (user_id = (select auth.uid()));

-- DELETE: Users can only delete their own error logs
-- Allows users to clean up their error history if desired
create policy "generation_error_logs_delete_authenticated"
    on generation_error_logs for delete
    to authenticated
    using (user_id = (select auth.uid()));

-- ----------------------------------------------------------------------------
-- Triggers
-- ----------------------------------------------------------------------------

-- Trigger: Auto-update updated_at timestamp on flashcards
-- Uses moddatetime extension to automatically set updated_at to current timestamp
-- whenever a row is updated
create trigger handle_flashcards_updated_at
    before update on flashcards
    for each row
    execute function moddatetime(updated_at);